limit-special-things:
  interval: 15  # in secs
  max: 200      # number of requests per interval
  matches:      # which requests to apply this limit to
    paths:
      match_any:
        - "/special/resources/.*"
  keys:         # define dynamic bucket name
    headers:
      names:
        - "Authorization"
    ip:  

other-limit:
  interval: 10
  max: 10
  matches:
    headers:
      match_any:
        - name: "Content-Type"
          match: "Boo"
